#############################################################
### ------ Creating Deployment For Nginx/FRONTs ----------###
#############################################################
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: shell
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: shell
    spec:
      containers:
      - name: shell
        image: harbor.picsart.tools/analytics/shell:latest
        imagePullPolicy: Always
        env:
        - name: OWNER_PASSWD
          value: "satori"
        - name: OWNER_UID
          value: "1002"
        - name: OWNER_NAME
          value: "satori"
#        command: ['/bin/sh', '-c']
#        args: ['/etc/init.d/nginx stop && /usr/sbin/nginx -g "daemon off;" ']
        ports:
        - containerPort: 80
          name: http
        - containerPort: 3000
          name: https

      imagePullSecrets:
        - name: reg.harbor.picsart.tools
        - name: reg.hub.picsart.tools

